name: Deploy chalice project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Prerequisites
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy chalice
      run: |
        chalice deploy
